export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  RATE_LIMITED = 'RATE_LIMITED',
  BROKER_UNAVAILABLE = 'BROKER_UNAVAILABLE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
